deploy:
  provider: npm
  email: npm@foddys.com
  api_key:
    secure: aGXAwOP6F/NCJocALHMgzmYmS06EUjEU9NNtU4HlXEC8OD3lF4IU1EWOSkx1eApjxns1Pck0VlfDwh3d9cVHLCs3IyUayderUmi7IqHRFOKjKsuMfvVYN4MQlmgiM1HPn9hBj0aVdTtPhkdqE5cGh74KAuYh03fFFdlVh4OTDTpmr9L8+EHxRyHmvmqcnOXt5yBcPhlvEzJhK/f9I4rYD0YEUymQv4nBtfutyFtaIw8QPHPCHf6VZEhJwN7z6FJmjtiLRcumKzVYZVZDyTQzD1J+EQwtzpuOjLCaSjUuB47v3FYLsPHpINmEXkIp4lZRnc5p3Ink1Mts5Zj7xwJmZ04zBod21MNPKeAIEJuqJhdIMJ8qWnKoJwMKpCkvH0EoqpRr/rpTAyQYRMj+ZPM/7jjpHN+O+PNOvHgzY4fHNzaTzcfyOw3jY/srPGFfKuheFYT9vl1yxjY1RZ2qTKJeSrRoyfakJvEtH39ppBqXnYTBXtDr4KSzddQVN8dmoBVrtJL75JaTlmzV89l0RrrYwP8IVxXp3/+EVuXNi6hN9c6YKveqGcrGyDuRftKGdbXCTPGzbF/bBVB5fKJd8O1IYdbQ2gX5UPu3U0Td7sGQt9nuNCY3aL0W6+Q3IB3SGHy4HRbkFAh5XbEqmpaYM6Lm4+EuOrIB0qgxWeQmGgYnaU0=
  on:
    repo: Foddy/node-red-contrib-huemagic